# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 54eb4f36c18df60a029cd1c36f0082753ab0eb0812f1513b4e0cb8d3491584647e7b425859f1423b6501da6ed1c9d7fae9eeb4ffadba24110b8bdc33a696f950

test:
  secret_key_base: cd292631d45c81d812425c6a4d2857635f546e99fb5d82f1afedfbb7d1232ba33738025fda1298cad17ff10daefe4a7ca737cacb10ec83ef2e32037d3fac0b54

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
